name: Manual run testing

on:
  workflow_dispatch:
    inputs:
      application:
        type: choice
        description: Application
        options:
          - api
          - frontend
  push:
    branches:
      - main  # Thay đổi branch tùy vào yêu cầu của dự án

jobs:
  # call-test-on-circleci:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: ${{ github.event.inputs.branch }}
  #       name: checkout
  #     - name: Dispatch circleci workflow
  #       uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
  #       with:
  #         GHA_Meta: ${{ github.event.inputs.application }}
  #       env:
  #         CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
  
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  notify-push-event:
    runs-on: ubuntu-latest
    steps:
      - name: Notify push event
        run: echo "Push event detected on branch ${{ github.ref }}"